ATV_3bi/Models/Cliente.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ATV_3bi.Models
{
    public class Cliente
    {
        [Display(Name = "Nome:")]
        [Required(ErrorMessage = "Insira o nome")]
        public string CliNome { get; set; }

        [Display(Name = "CPF:")]
        [Required(ErrorMessage = "Insira o número do CPF")]
        public string CliCpf { get; set; }

        [Display(Name = "Data de Nascimento:")]
        [Required(ErrorMessage = "Insira a data de nascimento")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime CliDtNasc
        {
            get
            {
                return this.funcDtNasc.HasValue ? this.funcDtNasc.Value : DateTime.Now;
            }
            set
            {
                this.funcDtNasc = value;
            }
        }
        private DateTime? funcDtNasc = null;

        [Display(Name = "E-mail:")]
        [Required(ErrorMessage = "Insira o e-mail")]
        [RegularExpression(@"\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*", ErrorMessage = "Email inválido")]
        public string CliEmail { get; set; }

        [Display(Name = "Número de Celular:")]
        [Required(ErrorMessage = "Insira o número de celular")]
        public double CliCel { get; set; }

        [Display(Name = "Endereço:")]
        [Required(ErrorMessage = "Insira o endereço")]
        public string CliEnd { get; set; }
    }
}

ATV_3bi/Models/Funcionario.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ATV_3bi.Models
{
    public class Funcionario
    {
        [Display(Name = "Código do Funcionário:")]
        [Required (ErrorMessage = "Insira um código")]
        public int FuncCod { get; set; }

        [Display(Name = "Nome:")]
        [Required (ErrorMessage = "Insira o nome")]
        public string FuncNome { get; set; }

        [Display(Name = "CPF:")]
        [Required(ErrorMessage = "Insira o número do CPF")]
        public string FuncCpf { get; set; }

        [Display(Name = "RG:")]
        [Required(ErrorMessage = "Insira o número do RG")]
        public string FuncRg { get; set; }

        [Display(Name = "Data de Nascimento:")]
        [Required(ErrorMessage ="Insira a data de nascimento")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime FuncDtNasc
        {
            get
            {
                return this.funcDtNasc.HasValue ? this.funcDtNasc.Value : DateTime.Now;
            }
            set
            {
                this.FuncDtNasc = value;
            }
        }
        private DateTime? funcDtNasc = null;

        [Display(Name = "Endereço:")]
        [Required(ErrorMessage = "Insira o endereço")]
        public string FuncEnd { get; set; }

        [Display(Name = "Número de Celular:")]
        [Required(ErrorMessage = "Insira o número de celular")]
        public double FuncCel { get; set; }

        [Display(Name = "E-mail:")]
        [Required(ErrorMessage = "Insira o e-mail")]
        [RegularExpression(@"\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*", ErrorMessage = "Email inválido")]
        public string FuncEmail { get; set; }

        [Display(Name = "Cargo:")]
        [Required(ErrorMessage = "Insira o cargo")]
        public string FuncCargo { get; set; }
    }
}

ATV_3bi/Models/Jogo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ATV_3bi.Models
{
    public class Jogo
    {
        [Display(Name = "Código do Jogo:")]
        [Required(ErrorMessage = "Insira um código")]
        public int JogoCod { get; set; }

        [Display(Name = "Nome:")]
        [Required(ErrorMessage = "Insira o nome")]
        public string JogoNome { get; set; }

        [Display(Name = "Versão:")]
        public string JogoVersao { get; set; }

        [Display(Name = "Desenvolvedor:")]
        [Required(ErrorMessage = "Insira o desenvolvedor")]
        public string JogoDev { get; set; }

        [Display(Name = "Gênero:")]
        [Required(ErrorMessage = "Insira o gênero do jogo")]
        public string JogoGen { get; set; }

        [Display(Name = "Faixa Etária:")]
        [Required(ErrorMessage = "Insira a faixa etária")]
        public string JogoFxEt { get; set; }

        [Display(Name = "Plataforma:")]
        [Required(ErrorMessage = "Insira a plataforma")]
        public string JogoPlat { get; set; }

        [Display(Name = "Ano de Lançamento:")]
        [Required(ErrorMessage = "Insira o ano")]
        public double JogoAnoLanc { get; set; }

        [Display(Name = "Sinopse:")]
        [Required(ErrorMessage = "Insira a sinopse")]
        public string JogoSin { get; set; }
    }
}

ATV_3bi/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ATV_3bi.Models;

namespace ATV_3bi.Controllers
{
    public class ClienteController : Controller
    {
        // GET: Cliente
        public ActionResult IndexCli()
        {
            var cliente = new Cliente();
            return View(cliente);
        }

        Action ac = new Action();

        [HttpPost]

        public ActionResult IndexCli(Cliente cliente)
        {
            ac.CadastrarCliente(cliente);
            return View(cliente);
        }
        /*public ActionResult IndexCli(Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                return View("ListarCli", cliente);
            }
            return View(cliente);
        }
        public ActionResult ListarCli(Cliente cliente)
        {
            return View(cliente);
        }*/
    }
}

ATV_3bi/Controllers/FuncionarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ATV_3bi.Models;

namespace ATV_3bi.Controllers
{
    public class FuncionarioController : Controller
    {
        // GET: Funcionario
        public ActionResult IndexFunc()
        {
            var funcionario = new Funcionario();
            return View(funcionario);
        }

        Action ac = new Action();

        [HttpPost]
        
        public ActionResult IndexFunc (Funcionario funcionario)
        {
            ac.CadastrarFuncionario(funcionario);
            return View(funcionario);
        }
    }
}

ATV_3bi/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ATV_3bi.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ATV_3bi/Controllers/JogoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ATV_3bi.Models;

namespace ATV_3bi.Controllers
{
    public class JogoController : Controller
    {
        // GET: Jogo
        public ActionResult IndexJogo()
        {
            var jogo = new Jogo();
            return View(jogo);
        }

        Action ac = new Action();

        [HttpPost]

        public ActionResult IndexJogo(Jogo jogo)
        {
            ac.CadastrarJogo(jogo);
            return View(jogo);
        }
        /*public ActionResult IndexJogo(Jogo jogo)
        {
            if (ModelState.IsValid)
            {
                return View("ListarJogo", jogo);
            }
            return View(jogo);
        }
        public ActionResult ListarJogo(Jogo jogo)
        {
            return View(jogo);
        }*/
    }
}

ATV_3bi/Views/Cliente/IndexCli.cshtml
@model ATV_3bi.Models.Cliente
@{
    ViewBag.Title = "IndexCli";
}

<h3>Cadastrar Cliente</h3>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <fieldset>
        <div class="editor-label">
            @Html.LabelFor(m => m.CliNome)
        </div>
        <div class="editor-field">
            @Html.EditorFor(m => m.CliNome)
            @Html.ValidationMessageFor(m => m.CliNome)
        </div>

        <div class="editor-label">
            @Html.LabelFor(m => m.CliCpf)
        </div>
        <div class="editor-field">
            @Html.EditorFor(m => m.CliCpf)
            @Html.ValidationMessageFor(m => m.CliCpf)
        </div>

        <div class="editor-label">
            @Html.LabelFor(m => m.CliDtNasc)
        </div>
        <div class="editor-field">
            @Html.EditorFor(m => m.CliDtNasc)
            @Html.ValidationMessageFor(m => m.CliDtNasc)
        </div>

        <div class="editor-label">
            @Html.LabelFor(m => m.CliEmail)
        </div>
        <div class="editor-field">
            @Html.EditorFor(m => m.CliEmail)
            @Html.ValidationMessageFor(m => m.CliEmail)
        </div>

        <div class="editor-label">
            @Html.LabelFor(m => m.CliCel)
        </div>
        <div class="editor-field">
            @Html.EditorFor(m => m.CliCel)
            @Html.ValidationMessageFor(m => m.CliCel)
        </div>

        <div class="editor-label">
            @Html.LabelFor(m => m.CliEnd)
        </div>
        <div class="editor-field">
            @Html.EditorFor(m => m.CliEnd)
            @Html.ValidationMessageFor(m => m.CliEnd)
        </div>

        <br />
        <div>
            <input type="submit" value="Cadastrar" />
        </div>
    </fieldset>

    @section Scripts{@Scripts.Render("~/bundles/jqueryval")}
}

ATV_3bi/Views/Cliente/ListarCli.cshtml
@model ATV_3bi.Models.Cliente
@{
    ViewBag.Title = "ListarCli";
}

<h2>Cliente Cadastrado</h2>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <fieldset>
        <div class="editor-label">@Html.DisplayNameFor(m => m.CliNome)</div>
        <div class="editor-field">@Html.DisplayFor(m => m.CliNome)</div>

        <div class="editor-label">@Html.DisplayNameFor(m => m.CliCpf)</div>
        <div class="editor-field">@Html.DisplayFor(m => m.CliCpf)</div>

        <div class="editor-label">@Html.DisplayNameFor(m => m.CliDtNasc)</div>
        <div class="editor-field">@Html.DisplayFor(m => m.CliDtNasc)</div>

        <div class="editor-label">@Html.DisplayNameFor(m => m.CliEmail)</div>
        <div class="editor-field">@Html.DisplayFor(m => m.CliEmail)</div>

        <div class="editor-label">@Html.DisplayNameFor(m => m.CliCel)</div>
        <div class="editor-field">@Html.DisplayFor(m => m.CliCel)</div>

        <div class="editor-label">@Html.DisplayNameFor(m => m.CliEnd)</div>
        <div class="editor-field">@Html.DisplayFor(m => m.CliEnd)</div>

        <br />
        @Html.ActionLink("Voltar", "Index", "Home")
    </fieldset>
}

ATV_3bi/Views/Funcionario/IndexFunc.cshtml
@model ATV_3bi.Models.Funcionario
@{
    ViewBag.Title = "Index";
}

<h3>Cadastrar Funcionário</h3>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <fieldset>
        <div class="editor-label">
            @Html.LabelFor(m => m.FuncCod)
        </div>
        <div class="editor-field">
            @Html.EditorFor(m => m.FuncCod)
            @Html.ValidationMessageFor(m => m.FuncCod)
        </div>

        <div class="editor-label">
            @Html.LabelFor(m => m.FuncNome)
        </div>
        <div class="editor-field">
            @Html.EditorFor(m => m.FuncNome)
            @Html.ValidationMessageFor(m => m.FuncNome)
        </div>

        <div class="editor-label">
            @Html.LabelFor(m => m.FuncCpf)
        </div>
        <div class="editor-field">
            @Html.EditorFor(m => m.FuncCpf)
            @Html.ValidationMessageFor(m => m.FuncCpf)
        </div>

        <div class="editor-label">
            @Html.LabelFor(m => m.FuncRg)
        </div>
        <div class="editor-field">
            @Html.EditorFor(m => m.FuncRg)
            @Html.ValidationMessageFor(m => m.FuncRg)
        </div>

        <div class="editor-label">
            @Html.LabelFor(m => m.FuncDtNasc)
        </div>
        <div class="editor-field">
            @Html.EditorFor(m => m.FuncDtNasc)
            @Html.ValidationMessageFor(m => m.FuncDtNasc)
        </div>

        <div class="editor-label">
            @Html.LabelFor(m => m.FuncEnd)
        </div>
        <div class="editor-field">
            @Html.EditorFor(m => m.FuncEnd)
            @Html.ValidationMessageFor(m => m.FuncEnd)
        </div>

        <div class="editor-label">
            @Html.LabelFor(m => m.FuncCel)
        </div>
        <div class="editor-field">
            @Html.EditorFor(m => m.FuncCel)
            @Html.ValidationMessageFor(m => m.FuncCel)
        </div>

        <div class="editor-label">
            @Html.LabelFor(m => m.FuncEmail)
        </div>
        <div class="editor-field">
            @Html.EditorFor(m => m.FuncEmail)
            @Html.ValidationMessageFor(m => m.FuncEmail)
        </div>

        <div class="editor-label">
            @Html.LabelFor(m => m.FuncCargo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(m => m.FuncCargo)
            @Html.ValidationMessageFor(m => m.FuncCargo)
        </div>

        <br />
        <div>
            <input type="submit" value="Cadastrar"/>
        </div>
    </fieldset>

    @section Scripts{@Scripts.Render("~/bundles/jqueryval")}
}

ATV_3bi/Views/Funcionario/Listar.cshtml
@model ATV_3bi.Models.Funcionario
@{
    ViewBag.Title = "Listar";
}

<h2>Usuário Cadastrado</h2>
@using (Html.BeginForm())
 {
    @Html.ValidationSummary(true)
    <fieldset>
        <div class="editor-label">@Html.DisplayNameFor(m => m.FuncCod)</div>
        <div class="editor-field">@Html.DisplayFor(m => m.FuncCod)</div>

        <div class="editor-label">@Html.DisplayNameFor(m => m.FuncNome)</div>
        <div class="editor-field">@Html.DisplayFor(m => m.FuncNome)</div>

        <div class="editor-label">@Html.DisplayNameFor(m => m.FuncCpf)</div>
        <div class="editor-field">@Html.DisplayFor(m => m.FuncCpf)</div>

        <div class="editor-label">@Html.DisplayNameFor(m => m.FuncRg)</div>
        <div class="editor-field">@Html.DisplayFor(m => m.FuncRg)</div>

        <div class="editor-label">@Html.DisplayNameFor(m => m.FuncDtNasc)</div>
        <div class="editor-field">@Html.DisplayFor(m => m.FuncDtNasc)</div>

        <div class="editor-label">@Html.DisplayNameFor(m => m.FuncEnd)</div>
        <div class="editor-field">@Html.DisplayFor(m => m.FuncEnd)</div>

        <div class="editor-label">@Html.DisplayNameFor(m => m.FuncCel)</div>
        <div class="editor-field">@Html.DisplayFor(m => m.FuncCel)</div>

        <div class="editor-label">@Html.DisplayNameFor(m => m.FuncEmail)</div>
        <div class="editor-field">@Html.DisplayFor(m => m.FuncEmail)</div>

        <div class="editor-label">@Html.DisplayNameFor(m => m.FuncCargo)</div>
        <div class="editor-field">@Html.DisplayFor(m => m.FuncCargo)</div>

        <br />
        @Html.ActionLink("Voltar", "Index", "Home")
    </fieldset>
 }

ATV_3bi/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}


<br />
<h2>Cadastre funcionários, clientes e jogos acessando as páginas indicadas no menu!</h2>

ATV_3bi/Views/Jogo/IndexJogo.cshtml
@model ATV_3bi.Models.Jogo
@{
    ViewBag.Title = "IndexJogo";
}

<h3>Cadastro de Jogo</h3>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <fieldset>
        <div class="editor-label">
            @Html.LabelFor(m => m.JogoCod)
        </div>
        <div class="editor-field">
            @Html.EditorFor(m => m.JogoCod)
            @Html.ValidationMessageFor(m => m.JogoCod)
        </div>

        <div class="editor-label">
            @Html.LabelFor(m => m.JogoNome)
        </div>
        <div class="editor-field">
            @Html.EditorFor(m => m.JogoNome)
            @Html.ValidationMessageFor(m => m.JogoNome)
        </div>

        <div class="editor-label">
            @Html.LabelFor(m => m.JogoVersao)
        </div>
        <div class="editor-field">
            @Html.EditorFor(m => m.JogoVersao)
            @Html.ValidationMessageFor(m => m.JogoVersao)
        </div>

        <div class="editor-label">
            @Html.LabelFor(m => m.JogoDev)
        </div>
        <div class="editor-field">
            @Html.EditorFor(m => m.JogoDev)
            @Html.ValidationMessageFor(m => m.JogoDev)
        </div>

        <div class="editor-label">
            @Html.LabelFor(m => m.JogoGen)
        </div>
        <div class="editor-field">
            @Html.EditorFor(m => m.JogoGen)
            @Html.ValidationMessageFor(m => m.JogoGen)
        </div>

        <div class="editor-label">
            @Html.LabelFor(m => m.JogoFxEt)
        </div>
        <div class="editor-field">
            @Html.EditorFor(m => m.JogoFxEt)
            @Html.ValidationMessageFor(m => m.JogoFxEt)
        </div>

        <div class="editor-label">
            @Html.LabelFor(m => m.JogoPlat)
        </div>
        <div class="editor-field">
            @Html.EditorFor(m => m.JogoPlat)
            @Html.ValidationMessageFor(m => m.JogoPlat)
        </div>

        <div class="editor-label">
            @Html.LabelFor(m => m.JogoAnoLanc)
        </div>
        <div class="editor-field">
            @Html.EditorFor(m => m.JogoAnoLanc)
            @Html.ValidationMessageFor(m => m.JogoAnoLanc)
        </div>

        <div class="editor-label">
            @Html.LabelFor(m => m.JogoSin)
        </div>
        <div class="editor-field">
            @Html.EditorFor(m => m.JogoSin)
            @Html.ValidationMessageFor(m => m.JogoSin)
        </div>

        <br />
        <div>
            <input type="submit" value="Cadastrar" />
        </div>
    </fieldset>

    @section Scripts{@Scripts.Render("~/bundles/jqueryval")}
}

ATV_3bi/Views/Jogo/ListarJogo.cshtml
@model ATV_3bi.Models.Jogo
@{
    ViewBag.Title = "ListarJogo";
}

<h2>Jogo Cadastrado</h2>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <fieldset>
        <div class="editor-label">@Html.DisplayNameFor(m => m.JogoCod)</div>
        <div class="editor-field">@Html.DisplayFor(m => m.JogoCod)</div>

        <div class="editor-label">@Html.DisplayNameFor(m => m.JogoNome)</div>
        <div class="editor-field">@Html.DisplayFor(m => m.JogoNome)</div>

        <div class="editor-label">@Html.DisplayNameFor(m => m.JogoVersao)</div>
        <div class="editor-field">@Html.DisplayFor(m => m.JogoVersao)</div>

        <div class="editor-label">@Html.DisplayNameFor(m => m.JogoDev)</div>
        <div class="editor-field">@Html.DisplayFor(m => m.JogoDev)</div>

        <div class="editor-label">@Html.DisplayNameFor(m => m.JogoGen)</div>
        <div class="editor-field">@Html.DisplayFor(m => m.JogoGen)</div>

        <div class="editor-label">@Html.DisplayNameFor(m => m.JogoFxEt)</div>
        <div class="editor-field">@Html.DisplayFor(m => m.JogoFxEt)</div>

        <div class="editor-label">@Html.DisplayNameFor(m => m.JogoPlat)</div>
        <div class="editor-field">@Html.DisplayFor(m => m.JogoPlat)</div>

        <div class="editor-label">@Html.DisplayNameFor(m => m.JogoAnoLanc)</div>
        <div class="editor-field">@Html.DisplayFor(m => m.JogoAnoLanc)</div>

        <div class="editor-label">@Html.DisplayNameFor(m => m.JogoSin)</div>
        <div class="editor-field">@Html.DisplayFor(m => m.JogoSin)</div>

        <br />
        @Html.ActionLink("Voltar", "Index", "Home")
    </fieldset>
}

ATV_3bi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Jogatina Store", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Início", "Index", "Home")</li>
                    <li>@Html.ActionLink("Funcionário", "IndexFunc", "Funcionario")</li>
                    <li>@Html.ActionLink("Cliente", "IndexCli", "Cliente")</li>
                    <li>@Html.ActionLink("Jogo", "IndexJogo", "Jogo")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - BrenCompany 2021 - </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>